spring:
  h2:
    console:
      enabled: true
      # default path: h2-console
      path: /h2-ui
  datasource:
    url: jdbc:h2:mem:bookDb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
redis:
  host: localhost
  port: 6379